### PR TITLE
K7 Addition

### PR DESCRIPTION
**Pull request by yanike**
I've created a K7 android theme for developers to use on average or small resolution displays to see a good simulated representation of the application they're developing.

### CODE REVIEW

**Comment by codenameone** [comment]
Thanks

**Comment by yanike** [comment]
You're welcome! Thank You :)

I did notice that the "icon" for the K7 skin in the download section isn't pulling through, but the skin does correctly download. Can you help out with that?

**Comment by codenameone** [comment]
Thanks, I totally missed that in the deployment stage. Unfortunately that stage isn't completely automated as it should be. It should be fixed now :)

**Comment by yanike** [comment]
AWESOME! Thanks.

**Pull request merged**
